import type { Metadata } from "next";
import './globals.css';

import AppHeader from "@/components/global/AppHeader";
import AppFooter from "@/components/global/AppFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-[1280px] mx-auto flex flex-col justify-between min-h-screen">
        <AppHeader />

        <main className="basis-auto grow">
          {children}
        </main>

        <AppFooter />
      </body>
    </html>
  );
}
